### ISSUE TITLE
Application not Sending Data

### ISSUE THREAD

**Issue by SCAbruh** [TheStaticTurtle/OSC2MEETER#2]
![image_2023-03-01_135054426](https://user-images.githubusercontent.com/35113327/222236495-55e65737-97aa-4ee4-b0bc-cf8bdbc830f2.png)
I've managed to fix an issue with receiving osc data from touch osc by using 127.0.0.1 as the host, but levels/changes made in voicemeeter aren't being sent back through osc.

**Comment by TheStaticTurtle** [comment]
OSC uses UDP. It has no concept of connection. That is why you need to listen on a port and send back to an IP:PORT combo.

Did you use the correct ip:port ?

**Comment by SCAbruh** [comment]
Well, my current configuration looks like this. 
![image_2023-03-01_150342044](https://user-images.githubusercontent.com/35113327/222253204-0ade86de-2728-49c2-b457-1924a3e12283.png)
Using the localhost ip the console provided resulted in no functionality whatsoever

**Comment by TheStaticTurtle** [comment]
And what is the command you use to start it?

**Comment by SCAbruh** [comment]
I'm not sure I understand... Sorry, I'm still new to this. All I do is:

1. Launch Voicemeeter
2. Launch OSC2MEETER
3. Launch my TouchOSC project and set up the control
4. Open the TouchOSC connections panel
5. Add the previously shown connection.

https://user-images.githubusercontent.com/35113327/222796063-985668e5-0cc8-4055-9c9f-c1879a93e1f9.mp4

**Comment by TheStaticTurtle** [comment]
Ah
This is a command line tool, you'll need to start it from a command prompt.
I guess it's my bad for setting default args.

So,
To make this work, you'll need:
- The IP address of the computer/phone running the OSC client (if the client/server is on the same machine `127.0.0.1` is ok)
- The IP address of the computer running the OSC2MEETER app (if the client/server is on the same machine `127.0.0.1` is ok)
- The port on which OSC2MEETER will listen for client messages (from your Touch OSC config it will be `8000`)
- The port on which the client will listen for OSC2MEETER messages (from your Touch OSC config it will be `9000`)

Now in your touchosc client config set the:
 - Protocol to `UDP`
 - `Host` to the IP of the computer running the OSC2MEETER
 - `Send port` to the port number OSC2MEETER is listening to
 - `Receive port` to the port number on which the client will listen

Now, to start OSC2MEETER replace the `<....>` by the actual value:
```
OSC2MEETER.exe --listen <OSC2MEETER port> --port <client port> --sendip <client IP>
```

Assuming that you will run touchosc on the same machine and that the touchosc config is the one you will keep run this command: 
```
OSC2MEETER.exe --listen 8000 --port 9000 --sendip 127.0.0.1
```

**Comment by SCAbruh** [comment]
Yes, this worked! Thank you!

**Comment by SCAbruh** [comment]
Reopening this because everything **but** the levels seem to work. hoping I can solve this because it was my primary use case.
![image_2023-03-03_153021465](https://user-images.githubusercontent.com/35113327/222822933-20b283c3-825c-4e8e-82d0-4bce7dd3d17b.png)

**Comment by TheStaticTurtle** [comment]
Just tested this with all versions of voicemetter and it does work fine

Verify that you are using the right address:
  - ``/vm/strip/<bus id starting at 0>/level`` for input strips
  - ``/vm/bus/<bus id starting at 0>/level`` for output buses

First argument is the channel (0=left 1=right) and the second one is the value.

If you can't make it work you could try the [Protokol app from hexler](https://hexler.net/protokol) to try to receive all OSC messages
